/* 
 * Deed API
 *
 * Land Registry Deed API
 *
 * OpenAPI spec version: 2.3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PrivateIndividualName
    /// </summary>
    [DataContract]
    public partial class PrivateIndividualName :  IEquatable<PrivateIndividualName>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GenderEnum
        {
            
            /// <summary>
            /// Enum Male for "Male"
            /// </summary>
            [EnumMember(Value = "Male")]
            Male,
            
            /// <summary>
            /// Enum Female for "Female"
            /// </summary>
            [EnumMember(Value = "Female")]
            Female,
            
            /// <summary>
            /// Enum NotSpecified for "Not Specified"
            /// </summary>
            [EnumMember(Value = "Not Specified")]
            NotSpecified
        }

        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public GenderEnum? Gender { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateIndividualName" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PrivateIndividualName() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateIndividualName" /> class.
        /// </summary>
        /// <param name="Forename">Forename (required).</param>
        /// <param name="MiddleName">MiddleName.</param>
        /// <param name="Surname">Surname (required).</param>
        /// <param name="Dob">Dob (required).</param>
        /// <param name="Gender">Gender.</param>
        /// <param name="PhoneNumber">PhoneNumber (required).</param>
        /// <param name="Address">Address (required).</param>
        public PrivateIndividualName(string Forename = default(string), string MiddleName = default(string), string Surname = default(string), string Dob = default(string), GenderEnum? Gender = default(GenderEnum?), string PhoneNumber = default(string), string Address = default(string))
        {
            // to ensure "Forename" is required (not null)
            if (Forename == null)
            {
                throw new InvalidDataException("Forename is a required property for PrivateIndividualName and cannot be null");
            }
            else
            {
                this.Forename = Forename;
            }
            // to ensure "Surname" is required (not null)
            if (Surname == null)
            {
                throw new InvalidDataException("Surname is a required property for PrivateIndividualName and cannot be null");
            }
            else
            {
                this.Surname = Surname;
            }
            // to ensure "Dob" is required (not null)
            if (Dob == null)
            {
                throw new InvalidDataException("Dob is a required property for PrivateIndividualName and cannot be null");
            }
            else
            {
                this.Dob = Dob;
            }
            // to ensure "PhoneNumber" is required (not null)
            if (PhoneNumber == null)
            {
                throw new InvalidDataException("PhoneNumber is a required property for PrivateIndividualName and cannot be null");
            }
            else
            {
                this.PhoneNumber = PhoneNumber;
            }
            // to ensure "Address" is required (not null)
            if (Address == null)
            {
                throw new InvalidDataException("Address is a required property for PrivateIndividualName and cannot be null");
            }
            else
            {
                this.Address = Address;
            }
            this.MiddleName = MiddleName;
            this.Gender = Gender;
        }
        
        /// <summary>
        /// Gets or Sets Forename
        /// </summary>
        [DataMember(Name="forename", EmitDefaultValue=false)]
        public string Forename { get; set; }

        /// <summary>
        /// Gets or Sets MiddleName
        /// </summary>
        [DataMember(Name="middle_name", EmitDefaultValue=false)]
        public string MiddleName { get; set; }

        /// <summary>
        /// Gets or Sets Surname
        /// </summary>
        [DataMember(Name="surname", EmitDefaultValue=false)]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or Sets Dob
        /// </summary>
        [DataMember(Name="dob", EmitDefaultValue=false)]
        public string Dob { get; set; }


        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [DataMember(Name="phone_number", EmitDefaultValue=false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PrivateIndividualName {\n");
            sb.Append("  Forename: ").Append(Forename).Append("\n");
            sb.Append("  MiddleName: ").Append(MiddleName).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("  Dob: ").Append(Dob).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PrivateIndividualName);
        }

        /// <summary>
        /// Returns true if PrivateIndividualName instances are equal
        /// </summary>
        /// <param name="other">Instance of PrivateIndividualName to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrivateIndividualName other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Forename == other.Forename ||
                    this.Forename != null &&
                    this.Forename.Equals(other.Forename)
                ) && 
                (
                    this.MiddleName == other.MiddleName ||
                    this.MiddleName != null &&
                    this.MiddleName.Equals(other.MiddleName)
                ) && 
                (
                    this.Surname == other.Surname ||
                    this.Surname != null &&
                    this.Surname.Equals(other.Surname)
                ) && 
                (
                    this.Dob == other.Dob ||
                    this.Dob != null &&
                    this.Dob.Equals(other.Dob)
                ) && 
                (
                    this.Gender == other.Gender ||
                    this.Gender != null &&
                    this.Gender.Equals(other.Gender)
                ) && 
                (
                    this.PhoneNumber == other.PhoneNumber ||
                    this.PhoneNumber != null &&
                    this.PhoneNumber.Equals(other.PhoneNumber)
                ) && 
                (
                    this.Address == other.Address ||
                    this.Address != null &&
                    this.Address.Equals(other.Address)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Forename != null)
                    hash = hash * 59 + this.Forename.GetHashCode();
                if (this.MiddleName != null)
                    hash = hash * 59 + this.MiddleName.GetHashCode();
                if (this.Surname != null)
                    hash = hash * 59 + this.Surname.GetHashCode();
                if (this.Dob != null)
                    hash = hash * 59 + this.Dob.GetHashCode();
                if (this.Gender != null)
                    hash = hash * 59 + this.Gender.GetHashCode();
                if (this.PhoneNumber != null)
                    hash = hash * 59 + this.PhoneNumber.GetHashCode();
                if (this.Address != null)
                    hash = hash * 59 + this.Address.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Forename (string) pattern
            Regex regexForename = new Regex(@"^(?!\\s*$).+", RegexOptions.CultureInvariant);
            if (false == regexForename.Match(this.Forename).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Forename, must match a pattern of " + regexForename, new [] { "Forename" });
            }

            // MiddleName (string) pattern
            Regex regexMiddleName = new Regex(@"^(?!\\s*$).+", RegexOptions.CultureInvariant);
            if (false == regexMiddleName.Match(this.MiddleName).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MiddleName, must match a pattern of " + regexMiddleName, new [] { "MiddleName" });
            }

            // Surname (string) pattern
            Regex regexSurname = new Regex(@"^(?!\\s*$).+", RegexOptions.CultureInvariant);
            if (false == regexSurname.Match(this.Surname).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Surname, must match a pattern of " + regexSurname, new [] { "Surname" });
            }

            // Dob (string) pattern
            Regex regexDob = new Regex(@"^(0[1-9]|[12][0-9]|3[01])[\/\\-](0[1-9]|1[012])[\/\\-]\\d{4}$", RegexOptions.CultureInvariant);
            if (false == regexDob.Match(this.Dob).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Dob, must match a pattern of " + regexDob, new [] { "Dob" });
            }

            // PhoneNumber (string) pattern
            Regex regexPhoneNumber = new Regex(@"^(07[\\d]{9})$", RegexOptions.CultureInvariant);
            if (false == regexPhoneNumber.Match(this.PhoneNumber).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, must match a pattern of " + regexPhoneNumber, new [] { "PhoneNumber" });
            }

            // Address (string) pattern
            Regex regexAddress = new Regex(@"[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9](?:A-Z-245|[^CIKMOV]){2}", RegexOptions.CultureInvariant);
            if (false == regexAddress.Match(this.Address).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Address, must match a pattern of " + regexAddress, new [] { "Address" });
            }

            yield break;
        }
    }

}
