/* 
 * Deed API
 *
 * Land Registry Deed API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeedApplication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeedApplicationTests
    {
        private DeedApplication instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeedApplication();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeedApplication
        /// </summary>
        [Test]
        public void DeedApplicationInstanceTest()
        {
            Assert.IsInstanceOf<DeedApplication> (instance, "instance is a DeedApplication");
        }

        /// <summary>
        /// Test the property 'TitleNumber'
        /// </summary>
        [Test]
        public void TitleNumberTest()
        {
            // TODO: unit test for the property 'TitleNumber'
        }
        /// <summary>
        /// Test the property 'Borrowers'
        /// </summary>
        [Test]
        public void BorrowersTest()
        {
            // TODO: unit test for the property 'Borrowers'
        }
        /// <summary>
        /// Test the property 'MdRef'
        /// </summary>
        [Test]
        public void MdRefTest()
        {
            // TODO: unit test for the property 'MdRef'
        }
        /// <summary>
        /// Test the property 'IdentityChecked'
        /// </summary>
        [Test]
        public void IdentityCheckedTest()
        {
            // TODO: unit test for the property 'IdentityChecked'
        }
        /// <summary>
        /// Test the property 'PropertyAddress'
        /// </summary>
        [Test]
        public void PropertyAddressTest()
        {
            // TODO: unit test for the property 'PropertyAddress'
        }

    }

}
